from colorama import init, Fore, Style

init(autoreset=True)

def run():
    print(f"\n{Fore.CYAN}{'=' * 80}")
    print(f"{Fore.CYAN}║{Fore.GREEN}                    VulEye — COMPLETE USAGE GUIDE                          {Fore.CYAN} ║")
    print(f"{Fore.CYAN}{'=' * 80}{Style.RESET_ALL}")

    print(f"\n{Fore.YELLOW}🔍 What is VulEye?{Style.RESET_ALL}")
    print(f"   Unified security testing toolkit for ethical vulnerability assessment:")
    print(f"   • Network reconnaissance (port scanning, service enumeration)")
    print(f"   • Web application testing (injection flaws, XSS, misconfigurations)")
    print(f"   • Authentication testing (credential brute-forcing, session analysis)")
    print(f"   • System enumeration (Linux privilege escalation vectors)")
    print(f"   • Exploit database (CVE-indexed vulnerability references)")

    print(f"\n{Fore.RED}⚠️  CRITICAL LEGAL WARNING{Style.RESET_ALL}")
    print(f"   {Fore.RED}NEVER use this toolkit without explicit written authorization!{Style.RESET_ALL}")
    print(f"   • Unauthorized testing = criminal offense")
    print(f"     (Computer Fraud and Abuse Act (USA), Art. 272/273 CC RF (Russia))")
    print(f"   • Even on personal devices within corporate networks requires approval")
    print(f"   • All modules require explicit consent confirmation before execution")
    print(f"   • Maintain documentation of all authorized testing activities")

    print(f"\n{Fore.YELLOW}🎮 How to navigate the menu:{Style.RESET_ALL}")
    print(f"   1. Launch the toolkit:")
    print(f"      {Fore.GREEN}python3 main.py{Style.RESET_ALL}")
    print(f"\n   2. Main menu options:")
    print(f"      {Fore.CYAN}1. Modules{Style.RESET_ALL} → vulnerability scanners by category")
    print(f"      {Fore.CYAN}2. Core Tools{Style.RESET_ALL} → auxiliary utilities (including this help)")
    print(f"      {Fore.CYAN}3. Exploits Database{Style.RESET_ALL} → CVE-indexed vulnerability references")
    print(f"      {Fore.CYAN}0. Exit{Style.RESET_ALL} → terminate application")
    print(f"\n   3. Module selection workflow:")
    print(f"      • Select category (web/network/auth/config/info)")
    print(f"      • Choose vulnerability type by number")
    print(f"      • Follow on-screen prompts")
    print(f"      • Press Enter after completion to return to menu")

    print(f"\n{Fore.YELLOW}🧩 Vulnerability categories:{Style.RESET_ALL}")

    print(f"\n{Fore.CYAN}🌐 Web Application Vulnerabilities:{Style.RESET_ALL}")
    print(f"   • SQL Injection (error-based, boolean-based, time-based)")
    print(f"   • Cross-Site Scripting (reflected, stored, DOM-based)")
    print(f"   • Local File Inclusion / Path Traversal")
    print(f"   • Server-Side Request Forgery (SSRF)")
    print(f"   • XML External Entity (XXE) Injection")
    print(f"   • Cross-Origin Resource Sharing (CORS) Misconfiguration")
    print(f"   • Open Redirects")
    print(f"   • Cross-Site Request Forgery (CSRF)")
    print(f"   • Insecure Direct Object References (IDOR)")

    print(f"\n{Fore.CYAN}📡 Network Vulnerabilities:{Style.RESET_ALL}")
    print(f"   • Open port enumeration (TCP/UDP)")
    print(f"   • Service version detection")
    print(f"   • Subdomain enumeration")
    print(f"   • DNS zone transfer vulnerabilities")
    print(f"   • SMB share enumeration")

    print(f"\n{Fore.CYAN}🔑 Authentication Vulnerabilities:{Style.RESET_ALL}")
    print(f"   • Credential brute-forcing (SSH, FTP, HTTP forms)")
    print(f"   • Weak password policies")
    print(f"   • Session fixation vulnerabilities")
    print(f"   • Missing brute-force protection")

    print(f"\n{Fore.CYAN}⚙️  Configuration Vulnerabilities:{Style.RESET_ALL}")
    print(f"   • Missing security headers (CSP, HSTS, X-Frame-Options)")
    print(f"   • Exposed sensitive files (.git, backups, configs)")
    print(f"   • Directory listing enabled")
    print(f"   • Information disclosure via error messages")
    print(f"   • Cookie security misconfigurations (missing HttpOnly/Secure flags)")

    print(f"\n{Fore.CYAN}📊 Information Gathering:{Style.RESET_ALL}")
    print(f"   • Technology stack fingerprinting")
    print(f"   • CMS/framework detection")
    print(f"   • SSL/TLS configuration analysis")
    print(f"   • Certificate validation issues")

    print(f"\n{Fore.YELLOW}🛡️  LEGAL TESTING ENVIRONMENTS{Style.RESET_ALL}")
    print(f"   {Fore.GREEN}✅ VulnHub{Style.RESET_ALL} — Free vulnerable virtual machines")
    print(f"      https://www.vulnhub.com")
    print(f"      Examples: Metasploitable 2, Kioptrix series, DC series")
    print(f"\n   {Fore.GREEN}✅ Docker Vulnerable Apps{Style.RESET_ALL}")
    print(f"      docker run -p 80:80 vulnerables/web-dvwa          # Damn Vulnerable Web App")
    print(f"      docker run -p 3000:3000 bkimminich/juice-shop     # OWASP Juice Shop")
    print(f"      docker run -p 8080:8080 vulhub/struts2/s2-045      # Apache Struts RCE")
    print(f"\n   {Fore.GREEN}✅ TryHackMe{Style.RESET_ALL} — Beginner-friendly learning platform")
    print(f"      https://tryhackme.com (free account available)")
    print(f"\n   {Fore.GREEN}✅ HackTheBox{Style.RESET_ALL} — Advanced penetration testing labs")
    print(f"      https://www.hackthebox.com (free tier available)")
    print(f"\n   {Fore.RED}❌ STRICTLY PROHIBITED:{Style.RESET_ALL}")
    print(f"      • Scanning public websites without written permission")
    print(f"      • Testing employer systems without explicit authorization")
    print(f"      • Scanning cloud infrastructure (AWS, Azure, GCP) without owner consent")
    print(f"      • Any activity violating Computer Fraud and Abuse Act or local laws")

    print(f"\n{Fore.YELLOW}💡 Practical usage examples:{Style.RESET_ALL}")
    print(f"\n   Local network reconnaissance:")
    print(f"      1. Select: Modules → Network → Port Scanner")
    print(f"      2. Target: 192.168.1.100 (your vulnerable VM IP)")
    print(f"      3. Confirm authorization: yes")
    print(f"\n   Web application testing (DVWA):")
    print(f"      1. Launch: docker run -p 80:80 vulnerables/web-dvwa")
    print(f"      2. Select: Modules → Web → SQL Injection")
    print(f"      3. Target: http://localhost/vulnerabilities/sqli/?id=1&Submit=Submit")
    print(f"      4. Confirm authorization: yes")

    print(f"\n{Fore.YELLOW}📊 Reporting and documentation:{Style.RESET_ALL}")
    print(f"   • All scan results saved to {Fore.GREEN}reports/{Style.RESET_ALL} directory")
    print(f"   • JSON format with timestamps and vulnerability details")
    print(f"   • Execution logs: reports/vuleye.log")
    print(f"   • Maintain these records as legal proof of authorized testing")

    print(f"\n{Fore.YELLOW}⚖️  Legal protection best practices:{Style.RESET_ALL}")
    print(f"   Before ANY testing activity:")
    print(f"   1. Obtain {Fore.GREEN}written authorization{Style.RESET_ALL} signed by system owner")
    print(f"   2. Document scope: IP ranges, allowed techniques, time window")
    print(f"   3. Save screenshots of authorization documentation")
    print(f"   4. Maintain detailed activity logs for minimum 12 months")
    print(f"\n   This documentation is your primary defense against legal challenges.")

    print(f"\n{Fore.YELLOW}🌟 Ethical reminder:{Style.RESET_ALL}")
    print(f"   {Fore.CYAN}«With great power comes great responsibility.»{Style.RESET_ALL}")
    print(f"   • Vulnerability research strengthens security when conducted ethically")
    print(f"   • Unauthorized testing harms victims and damages security community reputation")
    print(f"   • Always prioritize defense over offense")
    print(f"   • Report discovered vulnerabilities responsibly to owners")

    print(f"\n{Fore.CYAN}{'=' * 80}")
    print(f"{Fore.GREEN}✅ Professional advice:{Style.RESET_ALL}")
    print(f"   «The best penetration testers don't seek automatic exploits.")
    print(f"    They methodically analyze systems, document every finding,")
    print(f"    and always operate with explicit written authorization.»")
    print(f"{Fore.CYAN}{'=' * 80}{Style.RESET_ALL}")

    print(f"\n{Fore.YELLOW}↩️  Navigation:{Style.RESET_ALL} Press Enter → Core Tools menu → Select '0' to return to Main Menu")
    input(f"\n{Fore.BLUE}Press Enter to continue...{Style.RESET_ALL}")